### ISSUE TITLE
`static` and `media` filestorage not working. 

### ISSUE THREAD

**Issue by unownone** [SmartShala/parikshana-backend#1]
Static and media storage of the server has been shifted from simple directory storage to block storage and is managed by [`min.io`](https://min.io). 

Currently the issue remains that We are unable to access `min.io`'s block storage from `Django`.
We are using: 
- `Django==4.0.6`
- `django-storages==1.12.3`
- `boto3==1.24.36`
- `botocore==1.27.36`

The issue we are facing is `error 403 forbidden` wheneever we are trying to collect static files .
command: `python manage.py collectstatic`

**Comment by dvaldivia** [comment]
are the public assets expected to be access without authentication? if so make the bucket public or the prefix within the bucket where the assets reside

**Comment by unownone** [comment]
@dvaldivia public assets are expected to be accessed without auth. And so is made in the admin console .
